language: go

go:
- '1.9.x' # for Google App Engine Standard Environment and Heroku
- '1.10.x'
- '1.11.x'

install:
- go get -v -t ./...

script:
- go test ./...

after_success:
- |
  if [[ "$TRAVIS_GO_VERSION" = 1.11.x ]]; then
    pip install --user codecov
    go get github.com/axw/gocov/gocov
    go get github.com/mattn/goveralls
    go get golang.org/x/tools/cmd/cover
    go test -covermode=count -coverprofile=coverage.txt ./...
    goveralls -coverprofile=coverage.txt -service=travis-ci
  fi

env:
  global:
    secure: pUlQstTJJW4ib9GwDY5RZ6j10o1bxsqIUK4ku/45TZYDvWA2pN7+sS3vo1m+rxKhuLHowKerB/OjGKileQOWtkSq5kcdj48B8GwrPX29OvieWMzvuZjUMR1nDYya5tXgtzUHyVOmTUKaqKA5Yc4VhB6baChoEpUGLe3FGRdQvBP+lNYsr/FgUvp9d4FBPn17t94shHV4eindGUwfNBL/9qu4LeFZ4HKvmu7FL9LaECk1Mf3VpxU2ichLEXBKpJ38tn7CmXzQvjw8EvuNc9jGPqscxDWfAEaUEWttwec+AWRQTTYZmnlx9JdmrLpCSNTiGPrdUtR+mgUWW6uKEhzeaTYUBnwZHczpCuPe5x3RIZJT9wFIiJ4nRId3ZJH9uOQjQTA8dlTjbtj8jxH5htiVK7u7qizK0cU6t+BkibCaoAisyTNOs3FfdRYpDsfPbVk7Hi/AnMTTmXaRL3tYsySZT4Vti+yGnxs15hjBjUwLoKn1qn+T9ZmKfxuwXcc0gT3Bpj0EwXp2P10GzWZCeC8e7VwISliUsuMsilF0xTD3W9JgLzbhqZPw3lFZRet/ouV4q5EMjVVXTL0Pb6KTyOu18cf+JJZztPl3sf4ol4DOpsE/5wdfd8KXt0glH33JFVPgnMO9EbRZjfHCUFzjpLWjL/6ERQgaC8NnYOnTZRktOu0=

deploy:
- provider: script
  script: .ci/propagate -r hangulize.js -t "$TRAVIS_TAG"
  skip_cleanup: true
  on:
    tags: true
    go: '1.11.x'

- provider: script
  script: .ci/propagate -r api.hangulize.org -t "$TRAVIS_TAG"
  skip_cleanup: true
  on:
    tags: true
    go: '1.9.x'

- provider: script
  script: .ci/propagate -r phonemize.herokuapp.com -d -b 'master'
  skip_cleanup: true
  on:
    tags: true
    go: '1.9.x'
